/**
 * Velvet Storm
 *
 * Thousands of glowing motes drift through a field generated by two moving
 * storm centers. The field curls, pulses, and folds over itself, so the
 * trails feel half like weather and half like velvet smoke.
 *
 * Mouse           : bend the storm toward the cursor
 * Space / Click   : clear the canvas
 * R               : reseed storm centers
 * 1 / 2 / 3       : switch palette
 */

final int W = 800;
final int H = 600;
final int N = 5200;

final float FIELD_SCALE = 0.0026;
final float FADE_ALPHA = 9;
final float PARTICLE_SPEED = 1.9;
final float DRAG = 0.94;

float[] px = new float[N];
float[] py = new float[N];
float[] vx = new float[N];
float[] vy = new float[N];
float[] life = new float[N];

float stormSeed;
float time;
int paletteMode = 0;

void settings() {
  size(W, H, P2D);
  smooth(4);
}

void setup() {
  colorMode(HSB, 360, 100, 100, 100);
  stormSeed = random(10000);
  clearCanvas();
  for (int i = 0; i < N; i++) resetParticle(i, true);
}

void draw() {
  noStroke();
  fill(bgHue(), bgSat(), bgBri(), FADE_ALPHA);
  rect(0, 0, width, height);

  strokeWeight(1.15);

  float c1x = width * 0.34 + sin(time * 0.73 + stormSeed) * 180;
  float c1y = height * 0.47 + cos(time * 0.51 + stormSeed * 0.3) * 150;
  float c2x = width * 0.66 + cos(time * 0.68 + stormSeed * 0.7) * 170;
  float c2y = height * 0.53 + sin(time * 0.57 + stormSeed * 0.5) * 140;

  blendMode(ADD);
  for (int i = 0; i < N; i++) {
    float ox = px[i];
    float oy = py[i];

    float angle = fieldAngle(px[i], py[i], c1x, c1y, c2x, c2y);
    vx[i] += cos(angle) * 0.22;
    vy[i] += sin(angle) * 0.22;

    float md = dist(px[i], py[i], mouseX, mouseY);
    if (md < 180) {
      float pull = map(md, 0, 180, 0.085, 0);
      float ma = atan2(mouseY - py[i], mouseX - px[i]);
      vx[i] += cos(ma) * pull;
      vy[i] += sin(ma) * pull;
    }

    vx[i] *= DRAG;
    vy[i] *= DRAG;

    float speed = sqrt(vx[i] * vx[i] + vy[i] * vy[i]);
    if (speed > PARTICLE_SPEED) {
      vx[i] = vx[i] / speed * PARTICLE_SPEED;
      vy[i] = vy[i] / speed * PARTICLE_SPEED;
    }

    px[i] += vx[i];
    py[i] += vy[i];
    life[i] -= 0.0045;

    if (outOfBounds(px[i], py[i]) || life[i] <= 0) {
      resetParticle(i, false);
      continue;
    }

    float hue = particleHue(px[i], py[i], speed);
    float sat = 42 + noise(px[i] * 0.004, py[i] * 0.004, time * 0.6) * 36;
    float bri = 40 + min(speed / PARTICLE_SPEED, 1) * 55;
    float alpha = 10 + life[i] * 35;

    stroke(hue, sat, bri, alpha);
    line(ox, oy, px[i], py[i]);
  }
  blendMode(BLEND);

  drawCenters(c1x, c1y, c2x, c2y);

  time += 0.010;
}

float fieldAngle(float x, float y, float c1x, float c1y, float c2x, float c2y) {
  float dx1 = x - c1x;
  float dy1 = y - c1y;
  float dx2 = x - c2x;
  float dy2 = y - c2y;

  float a1 = atan2(dy1, dx1) + HALF_PI;
  float a2 = atan2(dy2, dx2) - HALF_PI;

  float n = noise(x * FIELD_SCALE, y * FIELD_SCALE, stormSeed + time * 0.25);
  float bend = map(n, 0, 1, -1.2, 1.2);

  return lerpAngle(a1, a2, 0.5 + 0.35 * sin(time * 0.8)) + bend;
}

float lerpAngle(float a, float b, float amt) {
  float diff = atan2(sin(b - a), cos(b - a));
  return a + diff * amt;
}

boolean outOfBounds(float x, float y) {
  return x < -20 || x > width + 20 || y < -20 || y > height + 20;
}

void resetParticle(int i, boolean anywhere) {
  if (anywhere) {
    px[i] = random(width);
    py[i] = random(height);
  } else {
    float edge = random(4);
    if (edge < 1) {
      px[i] = random(width);
      py[i] = -8;
    } else if (edge < 2) {
      px[i] = width + 8;
      py[i] = random(height);
    } else if (edge < 3) {
      px[i] = random(width);
      py[i] = height + 8;
    } else {
      px[i] = -8;
      py[i] = random(height);
    }
  }

  float a = random(TWO_PI);
  vx[i] = cos(a) * random(0.2, 0.9);
  vy[i] = sin(a) * random(0.2, 0.9);
  life[i] = random(0.55, 1.0);
}

float particleHue(float x, float y, float speed) {
  float t = noise(x * 0.003, y * 0.003, time * 0.35);
  if (paletteMode == 0) return (320 + t * 45 + speed * 12) % 360;
  if (paletteMode == 1) return (185 + t * 55 + speed * 18) % 360;
  return (22 + t * 38 + speed * 10) % 360;
}

float bgHue() {
  if (paletteMode == 0) return 282;
  if (paletteMode == 1) return 212;
  return 18;
}

float bgSat() {
  if (paletteMode == 2) return 55;
  return 38;
}

float bgBri() {
  if (paletteMode == 0) return 6;
  if (paletteMode == 1) return 7;
  return 8;
}

void drawCenters(float c1x, float c1y, float c2x, float c2y) {
  noStroke();
  blendMode(ADD);
  fill(particleHue(c1x, c1y, 0), 35, 60, 8);
  ellipse(c1x, c1y, 120, 120);
  fill(particleHue(c2x, c2y, 0.5), 35, 60, 8);
  ellipse(c2x, c2y, 120, 120);
  blendMode(BLEND);
}

void clearCanvas() {
  background(bgHue(), bgSat(), bgBri());
}

void mousePressed() {
  clearCanvas();
}

void keyPressed() {
  if (key == ' ') clearCanvas();
  if (key == 'r' || key == 'R') {
    stormSeed = random(10000);
    time = random(100);
    clearCanvas();
    for (int i = 0; i < N; i++) resetParticle(i, true);
  }
  if (key == '1') {
    paletteMode = 0;
    clearCanvas();
  }
  if (key == '2') {
    paletteMode = 1;
    clearCanvas();
  }
  if (key == '3') {
    paletteMode = 2;
    clearCanvas();
  }
}
